package com.heon.light;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.utils.ScreenUtils;

public class LightGame extends ApplicationAdapter {
    private SpriteBatch batch;
    private Texture image;
    private Texture dot99, dot, dot2, dot3, dot4, dot5, dot6, dot7, dot8, dot9, dot10, dot11, dot12, dot13, dot14, dot15, dot16, dot17, dot18, dot19, dot20, dot21, dot22, dot23, dot24, dot25, dot26, dot27, dot28, dot29, dot30, dot31, dot32, dot33, dot34, dot35, dot36, dot37, dot38, dot39, dot40, dot41, dot42, dot43, dot44, dot45, dot46, dot47, dot48, dot49, dot50, dot51, dot52, dot53, dot54, dot55, dot56, dot57, dot58, dot59, dot60, dot61, dot62, dot63, dot64, dot65;
    private Texture dotHover;

    private static final int DOT_X = 100;
    private static final int DOT_Y = 100;
    private int dotWidth;
    private int dotHeight;

    @Override
    public void create() {
        batch = new SpriteBatch();
        image = new Texture("one.png");
        dot = new Texture("avater.png");
        dot2 = new Texture("avater2.png");
        dot3 = new Texture("avater3.png");
        dot4 = new Texture("avater4.png");
        dot5 = new Texture("avater run.png");
        dot6 = new Texture("avater run2.png");
        dot7 = new Texture("blue.png");
        dot8 = new Texture("Cdoor.png");
        dot9 = new Texture("door.png");
        dot10 = new Texture("fuze1.png");
        dot11 = new Texture("fuze2.png");
        dot12 = new Texture("fuze3.png");
        dot13 = new Texture("fuze4.png");
        dot14 = new Texture("fuze5.png");
        dot15 = new Texture("fuze6.png");
        dot16 = new Texture("fuze7.png");
        dot17 = new Texture("fuze8.png");
        dot18 = new Texture("fuze9.png");
        dot19 = new Texture("fuze10.png");
        dot20 = new Texture("fuze11.png");
        dot21 = new Texture("fuze12.png");
        dot22 = new Texture("fuze13.png");
        dot23 = new Texture("fuze14.png");
        dot24 = new Texture("fuze15.png");
        dot25 = new Texture("fuze16.png");
        dot26 = new Texture("fuze17.png");
        dot27 = new Texture("Gmirror.png");
        dot28 = new Texture("goal.png");
        dot29 = new Texture("green.png");
        dot30 = new Texture("lever.png");
        dot31 = new Texture("lever2.png");
        dot32 = new Texture("LGmirror.png");
        dot33 = new Texture("light.png");
        dot34 = new Texture("Lmirror.png");
        dot35 = new Texture("mirror.png");
        dot36 = new Texture("option.png");
        dot37 = new Texture("pause.png");
        dot38 = new Texture("prism.png");
        dot39 = new Texture("red.png");
        dot40 = new Texture("restart.png");
        dot41 = new Texture("stage1.png");
        dot42 = new Texture("stage2.png");
        dot43 = new Texture("stage3.png");
        dot44 = new Texture("stage4.png");
        dot45= new Texture("stage5.png");
        dot46 = new Texture("stage6.png");
        dot47 = new Texture("stage7.png");
        dot48 = new Texture("stage8.png");
        dot49 = new Texture("stage9.png");
        dot50 = new Texture("stage10.png");
        dot51 = new Texture("stage11.png");
        dot52 = new Texture("stage12.png");
        dot53 = new Texture("stage1_hover.png");
        dot54 = new Texture("stage2_hover.png");
        dot55 = new Texture("stage3_hover.png");
        dot56 = new Texture("stage4_hover.png");
        dot57 = new Texture("stage5_hover.png");
        dot58 = new Texture("stage6_hover.png");
        dot59 = new Texture("stage7_hover.png");
        dot60 = new Texture("stage8_hover.png");
        dot61 = new Texture("stage9_hover.png");
        dot62 = new Texture("stage10_hover.png");
        dot63 = new Texture("stage11_hover.png");
        dot64 = new Texture("stage12_hover.png");
        dot65 = new Texture("start.png");


        dotWidth = dot.getWidth();
        dotHeight = dot.getHeight();
        dotWidth = dot2.getWidth();
        dotHeight = dot2.getHeight();
        dotWidth = dot3.getWidth();
        dotHeight = dot3.getHeight();
        dotWidth = dot4.getWidth();
        dotHeight = dot4.getHeight();
        dotWidth = dot5.getWidth();
        dotHeight = dot5.getHeight();
        dotWidth = dot6.getWidth();
        dotHeight = dot6.getHeight();
        dotWidth = dot7.getWidth();
        dotHeight = dot7.getHeight();
        dotWidth = dot8.getWidth();
        dotHeight = dot8.getHeight();
        dotWidth = dot9.getWidth();
        dotHeight = dot9.getHeight();
        dotWidth = dot10.getWidth();
        dotHeight = dot10.getHeight();
        dotWidth = dot11.getWidth();
        dotHeight = dot11.getHeight();
        dotWidth = dot12.getWidth();
        dotHeight = dot12.getHeight();
        dotWidth = dot13.getWidth();
        dotHeight = dot13.getHeight();
        dotWidth = dot14.getWidth();
        dotHeight = dot14.getHeight();
        dotWidth = dot15.getWidth();
        dotHeight = dot15.getHeight();
        dotWidth = dot16.getWidth();
        dotHeight = dot16.getHeight();
        dotWidth = dot17.getWidth();
        dotHeight = dot17.getHeight();
        dotWidth = dot18.getWidth();
        dotHeight = dot18.getHeight();
        dotWidth = dot19.getWidth();
        dotHeight = dot19.getHeight();
        dotWidth = dot20.getWidth();
        dotHeight = dot20.getHeight();
        dotWidth = dot21.getWidth();
        dotHeight = dot21.getHeight();
        dotWidth = dot22.getWidth();
        dotHeight = dot22.getHeight();
        dotWidth = dot23.getWidth();
        dotHeight = dot23.getHeight();
        dotWidth = dot24.getWidth();
        dotHeight = dot24.getHeight();
        dotWidth = dot25.getWidth();
        dotHeight = dot25.getHeight();
        dotWidth = dot26.getWidth();
        dotHeight = dot26.getHeight();
        dotWidth = dot27.getWidth();
        dotHeight = dot27.getHeight();
        dotWidth = dot28.getWidth();
        dotHeight = dot28.getHeight();
        dotWidth = dot29.getWidth();
        dotHeight = dot29.getHeight();
        dotWidth = dot30.getWidth();
        dotHeight = dot30.getHeight();
        dotWidth = dot31.getWidth();
        dotHeight = dot31.getHeight();
        dotWidth = dot32.getWidth();
        dotHeight = dot32.getHeight();
        dotWidth = dot33.getWidth();
        dotHeight = dot33.getHeight();
        dotWidth = dot34.getWidth();
        dotHeight = dot34.getHeight();
        dotWidth = dot35.getWidth();
        dotHeight = dot35.getHeight();
        dotWidth = dot36.getWidth();
        dotHeight = dot36.getHeight();
        dotWidth = dot37.getWidth();
        dotHeight = dot37.getHeight();
        dotWidth = dot38.getWidth();
        dotHeight = dot38.getHeight();
        dotWidth = dot39.getWidth();
        dotHeight = dot39.getHeight();
        dotWidth = dot40.getWidth();
        dotHeight = dot40.getHeight();
        dotWidth = dot41.getWidth();
        dotHeight = dot41.getHeight();
        dotWidth = dot42.getWidth();
        dotHeight = dot42.getHeight();
        dotWidth = dot43.getWidth();
        dotHeight = dot43.getHeight();
        dotWidth = dot44.getWidth();
        dotHeight = dot44.getHeight();
        dotWidth = dot45.getWidth();
        dotHeight = dot45.getHeight();
        dotWidth = dot46.getWidth();
        dotHeight = dot46.getHeight();
        dotWidth = dot47.getWidth();
        dotHeight = dot47.getHeight();
        dotWidth = dot48.getWidth();
        dotHeight = dot48.getHeight();
        dotWidth = dot49.getWidth();
        dotHeight = dot49.getHeight();
        dotWidth = dot50.getWidth();
        dotHeight = dot50.getHeight();
        dotWidth = dot51.getWidth();
        dotHeight = dot51.getHeight();
        dotWidth = dot52.getWidth();
        dotHeight = dot52.getHeight();
        dotWidth = dot53.getWidth();
        dotHeight = dot53.getHeight();
        dotWidth = dot54.getWidth();
        dotHeight = dot54.getHeight();
        dotWidth = dot55.getWidth();
        dotHeight = dot55.getHeight();
        dotWidth = dot56.getWidth();
        dotHeight = dot56.getHeight();
        dotWidth = dot57.getWidth();
        dotHeight = dot57.getHeight();
        dotWidth = dot58.getWidth();
        dotHeight = dot58.getHeight();
        dotWidth = dot59.getWidth();
        dotHeight = dot59.getHeight();
        dotWidth = dot60.getWidth();
        dotHeight = dot60.getHeight();
        dotWidth = dot61.getWidth();
        dotHeight = dot61.getHeight();
        dotWidth = dot62.getWidth();
        dotHeight = dot62.getHeight();
        dotWidth = dot63.getWidth();
        dotHeight = dot63.getHeight();
        dotWidth = dot64.getWidth();
        dotHeight = dot64.getHeight();
        dotWidth = dot65.getWidth();
        dotHeight = dot65.getHeight();


    }

    @Override
    public void render() {
        ScreenUtils.clear(0.15f, 0.15f, 0.2f, 1f);

        int mouseX = Gdx.input.getX();
        int mouseY = Gdx.graphics.getHeight() - Gdx.input.getY();  // Y좌표는 반전해야 함

        boolean isMouseOverDot = mouseX >= DOT_X && mouseX <= DOT_X + dotWidth
            && mouseY >= DOT_Y && mouseY <= DOT_Y + dotHeight;

        batch.begin();
        batch.draw(image, 0, 0);
        batch.draw(dot,0, 0);
        batch.draw(dot2,20, 0);
        batch.draw(dot3,40, 0);
        batch.draw(dot4,60, 0);
        batch.draw(dot5,80, 0);
        batch.draw(dot6,100, 0);
        batch.draw(dot7,120, 0);
        batch.draw(dot8,140, 0);
        batch.draw(dot9,160, 0);
        batch.draw(dot10,180, 0);
        batch.draw(dot11,200, 0);
        batch.draw(dot12,220, 0);
        batch.draw(dot13,240, 0);
        batch.draw(dot14,260, 0);
        batch.draw(dot15,280, 0);
        batch.draw(dot16,300, 0);
        batch.draw(dot17,320, 0);
        batch.draw(dot18,340, 0);
        batch.draw(dot19,360, 0);
        batch.draw(dot20,380, 0);
        batch.draw(dot21,400, 0);
        batch.draw(dot22,420, 0);
        batch.draw(dot23,440, 0);
        batch.draw(dot24,460, 0);
        batch.draw(dot25,480, 0);
        batch.draw(dot26,500, 0);
        batch.draw(dot27,520, 0);
        batch.draw(dot28,540, 0);
        batch.draw(dot29,560, 0);
        batch.draw(dot30,580, 0);
        batch.draw(dot31,600, 0);
        batch.draw(dot32,620, 0);
        batch.draw(dot33,640, 0);
        batch.draw(dot34,660, 0);
        batch.draw(dot35,680, 0);
        batch.draw(dot36,700, 0);
        batch.draw(dot37,720, 0);
        batch.draw(dot38,740, 0);
        batch.draw(dot39,760, 0);
        batch.draw(dot40,780, 0);
        batch.draw(dot41,0, 100);
        batch.draw(dot42,100, 100);
        batch.draw(dot43,200, 100);
        batch.draw(dot44,300, 100);
        batch.draw(dot45,400, 100);
        batch.draw(dot46,500, 100);
        batch.draw(dot47,600, 100);
        batch.draw(dot48,700, 100);
        batch.draw(dot49,800, 100);
        batch.draw(dot50,900, 100);
        batch.draw(dot51,0, 200);
        batch.draw(dot52,100, 200);
        batch.draw(dot53,200, 200);
        batch.draw(dot54,300, 200);
        batch.draw(dot55,400, 200);
        batch.draw(dot56,500, 200);
        batch.draw(dot57,600, 200);
        batch.draw(dot58,700, 200);
        batch.draw(dot59,800, 200);
        batch.draw(dot60,900, 200);
        batch.draw(dot61,0, 300);
        batch.draw(dot62,100, 300);
        batch.draw(dot63,200, 300);
        batch.draw(dot64,300, 300);
        batch.draw(dot65,400, 300);



        batch.draw(isMouseOverDot ? dotHover : dot, DOT_X, DOT_Y);
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        image.dispose();
        dot.dispose();
        dot2.dispose();
        dot3.dispose();
        dot4.dispose();
        dot5.dispose();
        dot6.dispose();
        dot7.dispose();
        dot8.dispose();
        dot9.dispose();
        dot10.dispose();
        dot11.dispose();
        dot12.dispose();
        dot13.dispose();
        dot14.dispose();
        dot15.dispose();
        dot16.dispose();
        dot17.dispose();
        dot18.dispose();
        dot19.dispose();
        dot20.dispose();
        dot21.dispose();
        dot22.dispose();
        dot23.dispose();
        dot24.dispose();
        dot25.dispose();
        dot26.dispose();
        dot27.dispose();
        dot28.dispose();
        dot29.dispose();
        dot30.dispose();
        dot31.dispose();
        dot32.dispose();
        dot33.dispose();
        dot34.dispose();
        dot35.dispose();
        dot36.dispose();
        dot37.dispose();
        dot38.dispose();
        dot39.dispose();
        dot40.dispose();
        dot41.dispose();
        dot42.dispose();
        dot43.dispose();
        dot44.dispose();
        dot45.dispose();
        dot46.dispose();
        dot47.dispose();
        dot48.dispose();
        dot49.dispose();
        dot50.dispose();
        dot51.dispose();
        dot52.dispose();
        dot53.dispose();
        dot54.dispose();
        dot55.dispose();
        dot56.dispose();
        dot57.dispose();
        dot58.dispose();
        dot59.dispose();
        dot60.dispose();
        dot61.dispose();
        dot62.dispose();
        dot63.dispose();
        dot64.dispose();
        dot65.dispose();



        dotHover.dispose();
    }
}
